version: '3.8'

services:
  python:
    image: "${DOCKER_IMAGE}"
    volumes:
      - ./:/proj
    tty: true
    env_file: ./.env
    environment:
      DOCKER_HASH: ${DOCKER_HASH}
      GIT_HASH: ${GIT_HASH}
