version: '3.8'

services:
  python:
    image: "njroberts/blobfish-python@sha256:4cb4d04766c8e0f6b8b0394c374e73cebf1ab82c38f378b00b3071f220348291"
    volumes:
      - ./:/proj
    tty: true
    env_file: ./.env
    networks:
      - graph-net
  graphdb:
    image: ontotext/graphdb:10.2.1
    container_name: db
    volumes:
      - ./graphdb-data/home:/opt/graphdb/home
    ports:
      - "7200:7200"
    networks:
      - graph-net
networks:
  graph-net:
    driver: bridge
