version: '3.8'

services:
  python:
    image: "${DOCKER_IMAGE}"
    volumes:
      - ./:/proj
    tty: true
    env_file: ./.env
    environment:
      DOCKER_IMAGE: ${DOCKER_IMAGE}
      DOCKER_URL: ${DOCKER_URL}
      DOCKER_HASH: ${DOCKER_HASH}
      DOCKER_FILE_PATH: ${DOCKER_FILE_PATH}
      COMPOSE_FILE_PATH: ${COMPOSE_FILE_PATH}
      GIT_REPO: ${GIT_REPO}
      GIT_HASH: ${GIT_HASH}
